name: esaa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3 #latest version
  fluttertoast: ^8.0.9
  flutter_auth: ^0.0.1
  intl: ^0.17.0
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.7
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.8
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  flutter_stripe: ^5.1.0
  http: ^0.13.5
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  firebase_messaging:
  flutter_local_notifications:
  overlay_support:
  firebase_analytics:
    #google_fonts_arabic: ^1.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

